name: "students4students"
url: "localhost:4000"

paginate: 5
paginate_path: "/blog/page:num/"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"		  
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"